### ISSUE TITLE
Default value for custom input

### ISSUE THREAD

**Issue by jasondibenedetto** [bluebill1049/react-hook-form#103]
I've been running into an issue when trying to set a default value for a custom input component. I've experimented with using `getValues()` and `watch`, but both return an empty value on the first render.

See below to replicate the issue. The custom input field is empty on load, but will populate after entering text in any of the other fields.
https://codesandbox.io/s/react-hook-form-bug-2ltts

**Comment by bluebill1049** [comment]
Hi @jasondibenedetto ,

Thanks for reporting this issue.

For custom input, you will have to register the `defaultValue` manually. Because running the following code 

`register({ name: 'test' })` 

doesn't give React Hook Form the context of its ref. Your default value will be injected into the hook but not on the DOM input.

vice versa when you running `<input ref={register} />` React Hook Form have access to your input and hence it's working.

so for custom input, you will have to do `<input value={defaulValues.xxx} />`

`watch` will always return undefined for the initial render, it watches when the input changes. 

let me know if this makes sense.

cheers
bill

**Comment by jasondibenedetto** [comment]
That all makes sense to me, thank you for the direction @bluebill1049

**Comment by bluebill1049** [comment]
my pleasure, feel free to ask more questions or raise issues here.

have a nice day :)

**Comment by DeepeshKr** [comment]
I am trying to get existing values to show up in the form with delay (to simulate remote fetch) but the form does not update, or i am doing something wrong or missing something here... any clues?

https://codesandbox.io/s/react-hook-form-bug-bh5kh
