### ISSUE TITLE
Improve DX for removing a value from an index in an array

### ISSUE THREAD

**Issue by stramel** [bluebill1049/react-hook-form#144]
Currently, when using the array syntax. To be able to remove an item at a specific index, you must generate a unique key in an associated array. There is no good way to easily remove a specific index using a generated array.

Really just looking for either direction on how to easily accomplish this or discuss a way to improve the DX.

https://codesandbox.io/s/react-hook-form-array-fields-bwvhf

**Expected behavior**
Be able to remove an item from an array easily

**Comment by bluebill1049** [comment]
Thanks @stramel 

Do you have any good suggestion on top of your head?

**Comment by stramel** [comment]
@bluebill1049 I don't have any good suggestions right now. I will try to think about it.

**Comment by bluebill1049** [comment]
yea I will keep that in mind as well. if anyone has a good idea, feel free to drop in this issue. we can all improve the DX for this particular issue.

**Comment by leapful** [comment]
@stramel For dynamic form array, I usually use an array of form control object as state to hold input value. When removing an input, we just need to remove the form control object at target index and then perform a re-rendering the rest form control object in array.

For example, in your codesandbox sample:
```javascript
  const [names, setNames] = useState([{ value: "" }]);

  const onAddPerson = () => setNames(previous => [...previous, { value: "" }]);

  const onChangePerson = idx => {
    return evt => {
      const newData = names.map((p, i) => {
        if (i !== idx) {
          return p;
        }
        return { ...p, value: evt.target && evt.target.value };
      });

      setNames(newData);
    };
  };

  const onRemovePerson = idx => {
    return () => {
      setNames(names.filter((p, i) => i !== idx));
    };
  };

  ...
  // "value" and "onChange" are used to update value in form control object
  {names.map((control, index) => {
          const inputKey = `name[${index}]`;

          return (
            <div>
              <label htmlFor={inputKey}>
                Name {index + 1}
                <div style={{ display: "flex" }}>
                  <input
                    id={inputKey}
                    name={inputKey}
                    placeholder={"Name " + (index + 1)}
                    value={control.value}
                    onChange={onChangePerson(index)}
                    ref={register}
                  />
                  <button
                    style={{ background: "#ec598f" }}
                    type="button"
                    onClick={onRemovePerson(index)}
                  >
                    X
                  </button>
                </div>
              </label>
              <hr />
            </div>
          );
        })}

```

Working sample:
https://codesandbox.io/s/react-hook-form-array-fields-24s7p

It's simple and clean enough to me. Hope you feel the same.

Note: I've changed input name attribute in your sample to match the sequence of form array that starts with 0, and only keep the label as index + 1 to avoid wrong submit values. React form hook will set value to form array by using input name attribute with index, if the name attribute is "name[1]", the form array is [null, value of name[1]] because there is no "name[0]".

P.S: There is only one problem when working with form array by using react form hook is that event "input" is always triggered when using recent suggestion input value of browser (autocomplete) and causes a wrong rendering but it's another issue.

**Comment by bluebill1049** [comment]
> P.S: There is only one problem when working with form array by using react form hook is that event "input" is always triggered when using recent suggestion input value of browser (autocomplete) and causes a wrong rendering but it's another issue.

curious to know the detail of this one @leapful

**Comment by leapful** [comment]
@bluebill1049 When using suggested value form last input of browser, it will trigger event listener of "input" event that is registed in

https://github.com/bluebill1049/react-hook-form/blob/a9409ef0787b263d227ac004d5259feb80ef38dd/src/logic/attachEventListeners.ts#L16

The listener performs validateAndStateUpdate() callback in 
https://github.com/bluebill1049/react-hook-form/blob/41374ccf58116a2f446ff47e3be43edaf98409ff/src/useForm.ts#L225

that also triggers a re-rendering.

At this time, the selected value is cleared because input value is not updated to form control object (onChange is not fired for change in text content).

You can re-produce this issue on my codesandbox sample above. Just type a value then submit and refresh the page. After that, click on input field to select suggested value from last input.

**Comment by bluebill1049** [comment]
thanks @leapful I will followup that issue.

**Comment by bluebill1049** [comment]
can you provide a codesandbox for this issue? @leapful

**Comment by bluebill1049** [comment]
i am closing this issue, feel free to re-open if anyone has better suggestion or solution.
