### ISSUE TITLE
Remove `submitFocusError` API

### ISSUE THREAD

**Issue by bluebill1049** [bluebill1049/react-hook-form#182]
Hey @barrymay  @stramel,

Quick question: your guys' thought over:

Remove `submitFocusError` and change to `focus` as an option for `useForm`

```
focus: {
  onSubmitError: false, // focus on the error input on submit
  onInputMount: false, // auto focus when first input mount
}
```

**Comment by barrymay** [comment]
Hi @bluebill1049  - it's a good question - and I'll welcome @stramel 's feedback as well.

I think submitFocusError makes sense, but what about letting the focus be based on an event when launched?  I personally think this change is not that needed, since the focusing should be part of the React component, and the form controlling it is overkill to me.

**Comment by bluebill1049** [comment]
Yea thanks @barrymay I did consider that u can do ‘autofocus’ urself on the input. 

I was thinking situation when u re-order the inputs, it will auto focus the first input. But I do agree with you and will leave this unchanged.

**Comment by barrymay** [comment]
Cool - I think if someone reorder's their inputs, they can feel free to be responsible to fix their own bug.  ;)

Best thing you can do for anyone here is to have the example of how to focus within one of the site examples, and they can just follow your example.

**Comment by bluebill1049** [comment]
sounds good to me @barrymay
