### ISSUE TITLE
Unmounting and re-mounting existing fields gives weird issues

### ISSUE THREAD

**Issue by Nickman87** [bluebill1049/react-hook-form#186]
**Describe the bug**
I'm making a wizard type input flow and thus I'm mounting and unmounting input fields whenever I need them.
In this flow I'm using a mix of manual inputs and actual registered components. De manual input is stable and works as expected. The registered one however does not.

1. When re-mounting it, it forgets it's previously set value
2. In my actual implementation, my watch often doesn't get registered properly or something and I do not get component updates when I type in the input (it seems to be working stable in my sample...)

**To Reproduce**
I've made a small copy of my setup here: https://codesandbox.io/s/react-hook-form-basic-tqfe9?fontsize=14

The first button input is completely manual and if you go back to that step, you will see that your choice is correctly remembered.
The second input is a number input, if you have entered something I want to show a next button (therefore the watch) and I also want to move to the next panel if you press enter (therefore the strange register code).
If you enter an age and come back to that panel, you will see that it is empty.

**Expected behavior**
As the field is registered, and the value is entered into the form, I would expect it to remain there and when I re-mount the input field with the same name, that I see my previous value again.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 76.0.3809.87 (64-bits)

**Comment by bluebill1049** [comment]
This is actually the expected behavior:

1. for registered input with ref, when input unmount. The input will get automatically `unregistered` hence value is lost
2. for custom registered input without ref, when input unmount. you will have to manually `unregister` yourself to during `useEffect` ( i will update that in the documentation)

- Solution:
1. To achieve your Wizzard form. I would recommend using `validationFields`, so restrict fields to be validated per step. So you basically show and hide inputs.
2. Build the form to remember input state with state management lib: I have built one maybe can be useful to you https://github.com/bluebill1049/little-state-machine

**Comment by Nickman87** [comment]
That seems a bit extreme for a simple usecase not? I mean, a simple boolean inside react-hook-form that switched between remembering and forgetting would be enough to make this work I think?

**Comment by bluebill1049** [comment]
your example unmounts a component, it shouldn't remember the state.

**Comment by bluebill1049** [comment]
as long as you do not unmount the input, then the state will remain. Just like a normal input component.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-unmounting-fields-0tvoe

**Comment by Nickman87** [comment]
So you would suggest keeping the components mounted and just toggle their visibility.
That way hook-form can still manage the state and do the validations.
I'll think about a bit and see what would work best for me.

Thanks you for your time!
