### ISSUE TITLE
[Question] Why state of form is not public (only available in submit function)?

### ISSUE THREAD

**Issue by AskAlexSharov** [bluebill1049/react-hook-form#29]
Currently state of form (data) available only in `handleSubmit` or `watch`.
Why don't make it public - similar to `useState` hook?

Opinion about `watch`:
As I understand `hooks` based architecture doesn't use "subscriptions". 
Subscriptions are from `reactive programming`.

**Comment by bluebill1049** [comment]
hi there,

One of the key difference for React Hook Form compare with other libs out there is with hook form it relies on uncontrolled input rather than control, so one problem is resolved is not re-render the form all the time when the user tries to type. but the lib does give the option to `watch` the fields change if you want to read state change.

I also want to distinguish between valid data and ones in progress.

when you hit `handleSubmit` the data is ready and pass all validation. with `watch`, you basically read what's on the input fields. 

for me `watch` is more useful when you want to enable another set of value or fields base on a particular input result. 

like this example: https://codesandbox.io/s/13ykqx4wx7

hope this makes sense.

cheers
bill

**Comment by AskAlexSharov** [comment]
"not re-render the form all the time when the user tries to type" - good result.

about `watch`: 
Ah, I miss-understood signature of `watch`. It's hook, not event listener with callback. Now all make sense for me.
