### ISSUE TITLE
Debounce async validation function calls when mode is `onChange`

### ISSUE THREAD

**Issue by gsoverini** [bluebill1049/react-hook-form#40]
Hi guys — First of all, thumbs up for this super cool library 👍

I recently noticed that when the validation mode in `onChange` and I have a field which performs async validation, the function is called every time the field changes, which is kind of wasteful. It would be nice to have a debounce functionality so the async function isn't called every time.
The usual scenario si when a user is typing on a field and I only want to validate when the typing is done, I don't care about validating on each keystroke.
This behavior is slightly better IMHO than the `onBlur` alternative, because the user could get a feedback when the focus is still on the field that is being filled in. And the feedback shouldn't "harass" the user. 

Please see this example for reference (open the dev console and type in the `Username` field).
https://codesandbox.io/s/react-hook-form-async-field-validation-50cyw

Is there a way I can achieve debouncing already? Am I missing something?
Thanks for your attention.

**Comment by bluebill1049** [comment]
hey @gsoverini,

Thank you ❤️for the kind word!

I think you can archive this by wrap around this?

```
import debounce from 'lodash/debounce';

validate: debounce(async value => {
  await sleep(300);
  return value === "bill";
})
```

This is what's in my head, I haven't tested it :)
I can spend some time do a demo for you too

cheers
bill

**Comment by bluebill1049** [comment]
hopefully, this answer your question, I am going to close this issue unless you have other questions :)

by the way here is a working version: https://codesandbox.io/s/xrjv48o0qp

**Comment by milesrichardson** [comment]
FYI, the above solution did not work for me because `debounce()` will not automatically return the value of its async callee. This is the approach I took:

```javascript
import debounce from "lodash.debounce";

const SomeComponent = () => {
  const { register, errors } = useForm({ mode: "onChange" });

  return (
    <Input
      id="username"
      name="username"
      error={errors.username}
      type="username"
      defaultValue={username}
      ref={register({
        required: "Username is required",
        validate: async value => {
          return new Promise(resolve => {
            debounce(
              async username => {
                const {
                  isValid,
                  errorMessage
                } = await MyAPILibrary.User.validateUsername(username);

                resolve(isValid || errorMessage);
              },
              500,
              { leading: true }
            )(value);
          });
        }
      })}
    />
  );
};
```

**Comment by bluebill1049** [comment]
@michaelbirchler you sure this is not going to work? i think i miss the duration as second argument
```
debounce(async function() {
    const response = await AlbumService.fetchAlbums();
    this.albums = response.data.albums;
  }, 1000)
```

**Comment by milesrichardson** [comment]
That will work, yeah, because you are setting the value of `this.albums` (outside the scope of the callback) from within the callback. But if the callback simply returned a boolean, it would not work.

i.e., this did not work for me:

```javascript
import debounce from "lodash.debounce";

const SomeComponent = () => {
  const { register, errors } = useForm({ mode: "onChange" });

  return (
    <Input
      id="username"
      name="username"
      error={errors.username}
      type="username"
      defaultValue={username}
      ref={register({
        required: "Username is required",
        validate: debounce(
          async value => {
            const {
              isValid,
              errorMessage
            } = await MyAPILibrary.User.validateUsername(value);

            return isValid || errorMessage;
          },
          500,
          { leading: true }
        )
      })}
    />
  );
};
```

I needed to wrap `debounce` with a Promise because `debounce` does not return a promise that resolves with the value of the function it's wrapping.

**Comment by bluebill1049** [comment]
@milesrichardson cool thanks for the quick response and info 👍

**Comment by i-ira** [comment]
> FYI, the above solution did not work for me because `debounce()` will not automatically return the value of its async callee. This is my working approach:
> 
> ```js
> import debounce from "lodash.debounce";
> 
> const SomeComponent = () => {
>   const { register, errors } = useForm({ mode: "onChange" });
> 
>   return (
>     <Input
>       id="username"
>       name="username"
>       error={errors.username}
>       type="username"
>       defaultValue={username}
>       ref={register({
>         required: "Username is required",
>         validate: async value => {
>           return new Promise(resolve => {
>             debounce(
>               async username => {
>                 const {
>                   isValid,
>                   errorMessage
>                 } = await MyAPILibrary.User.validateUsername(username);
> 
>                 resolve(isValid || errorMessage);
>               },
>               500,
>               { leading: true }
>             )(value);
>           });
>         }
>       })}
>     />
>   );
> };
> ```

for some reason, the timeout set in my debouncing call is not being respected as it fires instantly with every keystroke. below is my logic, any observations?

`validate: async value => {
	return new Promise(resolve => {
		debounce(
			async value => {
				const { data } = await axios.post('my.url', { value }) // returns a simple true or false
				resolve(data || 'that username is already in use, try another one')
			},
			600,
			{ leading: true }
		)(value)
        })
}`

**Comment by i-ira** [comment]
@milesrichardson for some reason, the timeout set in my debouncing call is not being respected as it fires instantly with every keystroke. below is my logic:

```javascript
validate: async value => {
  return new Promise(resolve => {
    debounce(
      async value => {
        const { data } = await axios.post('my.url', { value }) // returns a simple true or false
	resolve(data || 'that username is already in use, try another one')
      },
      600,
      { leading: true }
    )(value)
 })
}
```
any observations?

**Comment by durchanek** [comment]
For anyone looking for an easy solution, I solved this with [awesome-debounce-promise](https://github.com/slorber/awesome-debounce-promise)

```
validate: debouncePromise(async (value) => {
  return await validatePhoneNumber(value) || 'Phone number is invalid';
}, 500),
```

**Comment by bluebill1049** [comment]
wow thanks @durchanek

**Comment by mingsetl** [comment]
i managed to get it work by debouncing on the 'onChange' of the form item. for detailed solution, check out 'Trigger Validation' section in this post https://dragonza.io/use-debounce-in-react-hook-form-on-input-change/

**Comment by bluebill1049** [comment]
> i managed to get it work by debouncing on the 'onChange' of the form item. for detailed solution, check out 'Trigger Validation' section in this post https://dragonza.io/use-debounce-in-react-hook-form-on-input-change/

That's awesome! do you want to tweet this and we can share this in the community. You can send us a PR to include in the resource page as well.

**Comment by mercteil** [comment]
Thank you @mingsetl 

Had to debounce my api validation call which basically is a Promise. Since debounce does not return a promise I now ended up with a lightly different approach. Instead of using the onChange method I trigger the validation as a sideEffect

```javascript
  const triggerVatIdValidation = useCallback(
    debounce(250, () => {
      trigger('vatId');
    }),
    []
  );
  
  useEffect(() => {
    if (...some logic...) {        
     triggerVatIdValidation();
    }
  }, [watch('vatId')]);

**Comment by catalinberta** [comment]
I have had this problem too, where I wanted validation onChange, yet, not to be immediately shown and give the user a few seconds to at least try to type the expected value, like with e-mail fields.
After playing around with a few tricks trying to find the best UX, I've come to the realization that debouncing should only happen when first interacting with the field and not all the time.

Problems with debouncing validation:
- Even if you have validation `onChange`, you still have the Submit validation, you don't want the error to be delayed on submit
- Once the user has interacted and has seen the error, there is no point to keep debouncing, the user `needs` to instant feedback as he tried to correct the field value

My solution:
- Leave validation as is: onChange
- OnChange -> on first interacton (basically, when field becomes "dirty"), debounce the error's visibility

So if user types in an e-mail address, then the error message is only hidden the first time and given the time to type it out, afterwards it is shown normally, immediate.
Also, this rule ignores submit validation since it's on `onChange`

Not sure if that makes sense, I can try to create a demo if you want

**Comment by bluebill1049** [comment]
@catalinberta Thanks for providing the solution as above, and yes please share codesadnbox, it will help many others.

**Comment by catalinberta** [comment]
Ok, I've made a codesandbox of the above discussed behavior:

https://codesandbox.io/s/react-hook-form-debounce-field-validation-example-eufsh

I took an existent demo and added this behavior to illustrate the point. In reality, the code should be well refactored, such as the Input should probably be in its own component where it handles the debounce logic etc.

**Comment by oleksiikiselovartkai** [comment]
Hello everyone :wave: 

Just wondering if there is a working example with the debounce and `onChange` validation mode because right now neither of the suggested approaches works, and workaround with `useEffect` and `onChange` handlers add a lot of extra code and complexity when form grows bigger, would be very nice to make it work just in terms of the standard validation, thank you

**Comment by catalinberta** [comment]
Hey @oleksiikiselovartkai, 

Just curious, how do you see the previous solution adding to complexity along with bigger forms?
If the solution is implemented in a reusable component (i.e. you make a component `Input` including the solution and you always import that), it shouldn't add to complexity regardless of form size. 
I can update the demo to use a reusable component instead, if it's not clear

**Comment by oleksiikiselovartkai** [comment]
Hey @catalinberta,

Thank you for the help, I think making it reusable may help of course, but in case when I need to do some validation and then managed the state of the components based on that, for example disabling or enabling buttons and so forth, I have to keep track on all custom errors and so forth, while sync validators are handled by the `react-hook-form` which makes is more complex, also sometimes we might have a wizard form with multiple steps, so on every step change it might be required to revalidate values and so forth, while with built in validation it could be way more easier and in one place

Also just curios why debounce is not working inside the `validate` function, seems to be a common use case, probably I have to dig deeper into it in order to understand how it works under the hood

**Comment by milesrichardson** [comment]
Since this issue is active again I just want to mention that I ended up abandoning the debounce code I linked above; I offer no guarantees as to whether it works, lol.

FWIW -- in our setup, requests are going through apollo client, and so we used [apollo-link-debounce](https://github.com/helfer/apollo-link-debounce) to handle the debouncing at a lower level than in the form validation itself. This is a much cleaner approach but obviously won't work for everyone (although you could probably do something similar with a custom fetch implementation, and there).

**Comment by trumbitta** [comment]
> For anyone looking for an easy solution, I solved this with [awesome-debounce-promise](https://github.com/slorber/awesome-debounce-promise)
> 
> ```
> validate: debouncePromise(async (value) => {
>   return await validatePhoneNumber(value) || 'Phone number is invalid';
> }, 500),
> ```

Awesome and simple. Fantastic.

**Comment by oleksiikiselovartkai** [comment]
> > For anyone looking for an easy solution, I solved this with [awesome-debounce-promise](https://github.com/slorber/awesome-debounce-promise)
> > ```
> > validate: debouncePromise(async (value) => {
> >   return await validatePhoneNumber(value) || 'Phone number is invalid';
> > }, 500),
> > ```
> 
> Awesome and simple. Fantastic.

Hello @trumbitta 👋 

Is there any chance if you have a Sandbox example with this working approach or maybe a code snippet? I tried it as well and it did not work for me, but it would be great to have it working like that, so I am very curious 😄

**Comment by trumbitta** [comment]
@oleksiikiselovartkai I use RxJS so I fear my code could be very different from yours, but anyway:

```ts
const validatePhoneNumber = useCallback(
  (value: string) =>
    new ValidationApi()
      .validatePhoneNumber(value)
      .pipe(
        // API endpoint returns 400 on failed validation and 200 on successful validation
        catchError((error) => {
          // This makes the Promise reject
          return throwError(error)
        })
      )
      // Making it work with async/await
      .toPromise(),
  []
)

// ...more code

validate: AwesomeDebouncePromise(async (value: string) => {
  try {
    const results = await validatePhoneNumber(value)
    return true
  } catch (error) {
    return "Invalid phone number"
  }
}, 500)
```

**Comment by skhoroshavin** [comment]
FYI if you don't want to bring yet another external dep following TS snippet should also work:

```typescript
export function debounce<F extends (...args: any[]) => void>(func: F, wait?: number) {
    wait = wait || 100
    let timeoutID: any = null
    return function(this: any, ...args: Parameters<F>) {
        clearTimeout(timeoutID)
        timeoutID = setTimeout(() => func.apply(this, args), wait)
    } as F;
}

export function asyncDebounce<F extends (...args: any[]) => Promise<any>>(func: F, wait?: number) {
    const debounced = debounce((resolve: any, reject: any, args: Parameters<F>) => {
        func(...args).then(resolve).catch(reject);
    }, wait);

    return (...args: Parameters<F>): ReturnType<F> =>
        new Promise((resolve, reject) => {
            debounced(resolve, reject, args);
        }) as ReturnType<F>;
}

// ...more code

validate: asyncDebounce(async (value) => {
  return await validatePhoneNumber(value) || 'Phone number is invalid';
}, 500),
```

But this solution (as well as solutions based on `awesome-debounce-promise`) has a quirk - it will add delay to submission, because react-hook-form does additional validation right before submission, even if everything was already validated.

**Comment by young666** [comment]
> But this solution (as well as solutions based on `awesome-debounce-promise`) has a quirk - it will add delay to submission, because react-hook-form does additional validation right before submission, even if everything was already validated.
@skhoroshavin 
Yes, I have a really painful problem due to this, my idea is that I would manually trigger validation and debounce that trigger function, but it doesn't work. Do you have any solution for this @bluebill1049, can I have 'off' mode, which will turn off validation before submission?

**Comment by gituser3000** [comment]
@oleksiikiselovartkai 

```
import debounce from "awesome-debounce-promise";
const debouncedValidateEmail = useCallback(debounce(validateEmail, 700), []);

          {...register("Email", {
            validate: {
              unique: debouncedValidateEmail,
            },
```

**Comment by bluebill1049** [comment]
thanks for sharing solutions @gituser3000 validation need to be resilient on multiple invokes due to `onChange` and `formState` update (isValid), we did consider using the internal state to track validate fields but it's troublesome, especially validation can have its own scope of state update which hook form may not be aware. so it's always safer to re-run the validation which includes the coverage of external to make sure the field/form is valid.

**Comment by thefinnomenon** [comment]
I have a related issue,

@bluebill1049 I have a username input that I want to asynchronously verify as the user types (debounced) but I have two issues,

1. I don't want to set the whole form to validate onChange. Is it possible to only specify to validate the username input onChange?
2. Re-running the async validation on submit messes up the form UI because it makes the username field activity indicator show and, since the validation happens before the submit handler is even called, I have no way to trigger my submit activity indicator so the user's action seems like it wasn't even registered until the validation finally finishes and the submit button activity indicator shows. Is there a way to know this pre-submit validation is happening that way I can set isSubmitting there?

**Comment by jeremy8883** [comment]
I ended up using this [debounce-promise](https://github.com/bjoerge/debounce-promise) library instead of `awesome-debounce-promise`.

It allows me to set `leading` to `true`, so in most situations, I won't get a delay when the user clicks the submit button. It's not perfect, but my debounce timeout was only 200ms, so it was a good enough solution for me.

**Comment by rubengijbels** [comment]
for anyone wishing to do this now, here is a small wrapper around the register function which you can then use on your input field instead of the default register function:


```typescript
import { debounce } from 'debounce'
import { FieldPath, RegisterOptions, UseFormRegister, UseFormRegisterReturn, UseFormTrigger } from 'react-hook-form'

export const registerFieldWithDebounceValidation = <TFieldValues>(
  name: FieldPath<TFieldValues>,
  delay: number,
  trigger: UseFormTrigger<TFieldValues>,
  register: UseFormRegister<TFieldValues>,
  options?: RegisterOptions<TFieldValues, FieldPath<TFieldValues>>
) => {
  const useFormRegisterReturn: UseFormRegisterReturn = register(name, options)
  const { onChange } = useFormRegisterReturn
  const debouncedValidate = debounce(() => {
    trigger(name)
  }, delay)
  return {
    ...useFormRegisterReturn,
    onChange: (e: any) => {
      onChange(e)
      debouncedValidate()
    },
  }
}
```


to use it:
```typescript
<input {...registerFieldWithDebounceValidation('email', 1000, trigger, register)} />
```
