### ISSUE TITLE
Ability to transform value

### ISSUE THREAD

**Issue by GProst** [bluebill1049/react-hook-form#42]
Is there a way to apply value transformations on `cnange` event?
For example, I'd like to `trim()` some field values and if it's a credit card field I want to add white spaces after each 4th digit

**Comment by GProst** [comment]
Should have checked examples first, I forgot that setting `onChange` without `value` doesn't make an input controllable

**Comment by GProst** [comment]
On the second thought, can we really guarantee that `onChange` handler is called before the listener that is set by `react-hook-from` so that validations are run after the applied transformations?

Probably would be better if there was some `transformValue` property which we could pass to `register`

**Comment by bluebill1049** [comment]
very good point, I will spend figure out a good solution to this. Yea place inside `register` maybe a good idea.

**Comment by bluebill1049** [comment]
actually, we have this code in production. I can build a codesandbox on this.

```
<input
  name="customerEstimatedValue"
  onChange={e => {
    const value = e.target.value;
    const valueInNumber = convertStringToNumber(value);
    e.target.value = `$${valueInNumber.toLocaleString('en-IN')}`;
  }}
  ref={
    register({
        required: true,
        validate={{
          maxPropertyValue: value => convertStringToNumber(value) <= MAX_PROPERTY_VALUE,
          minPropertyValue: value => convertStringToNumber(value) > MIN_PROPERTY_VALUE,
        }}
   })
  }
/>
```

**Comment by GProst** [comment]
Hmm, indeed!
But I think this is nice if there is just one validation function otherwise the same transformation will be executed for each validation function + there is a code duplication

**Comment by bluebill1049** [comment]
Yea true that

**Comment by bluebill1049** [comment]
in terms of one validation function, we are actually only have one. 
```
import validatePropertyValue from './logic/validatePropertyValue';

ref={
  register({
  required: true,
  validate={validatePropertyValue}
})
```

I guess the only problem is here
```
onChange={e => {
    const value = e.target.value;
    const valueInNumber = convertStringToNumber(value);
    e.target.value = `$${valueInNumber.toLocaleString('en-IN')}`;
}}
```
but you can covert this into a funciton too
```
function maskValueInput() {
    const value = e.target.value;
    const valueInNumber = convertStringToNumber(value);
    e.target.value = `$${valueInNumber.toLocaleString('en-IN')}`;
}

onChange={maskValueInput}
```

or have a `transform` function in `register`.

one concern is that I am expanding the API, which you can achieve with normal Javascript. let me know about it 🤔

**Comment by GProst** [comment]
This is not something critical that I personally need, transforming `value` inside `validate` works for me 👍. Just feels like having something like `transform` in `register` would be convenient

**Comment by bluebill1049** [comment]
No worries I will park this for now then :) thanks

**Comment by cybervaldez** [comment]
I'm on the same boat, is there a new solution for transforming values after an input change but before a validation is triggered?

**Comment by bluebill1049** [comment]
the lib itself is not 1 year old :) 

alternative: you can custom register a field, 

```
useEffect(() => {
  register('test');
}, register);

<input onChange={e => {
  setValue('test', unTransform(e.target.value), true); // do you unTransform.
  e.target.value = 'xxx' // do you transform here;
}} />

```

**Comment by thefilmmaking** [comment]
@bluebill1049 first off, amazing lib, thank you for creating and maintaining this 🙏. Was wondering, on this topic, how do you feel about transforming the data in the onSubmit? Because I've been using this technique in many components now, especially for one or two fields to avoid full validation (via Yup) for the sake of simplicity. Example below. Let me know your thoughts, if any. Thanks again. 🙏

```
const onSubmit = data => {
data.title = data.title.trim();
// then send off data
}
```

**Comment by bluebill1049** [comment]
@thefilmmaking try this one: https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-52dvm

**Comment by david-morris** [comment]
Could we reopen this issue?  The lack of transform and parse options has painted me into a corner.

I have an input where I need to read a float, and have a blank space instead of NaN.  Using `register` doesn't serve this use case well, because there's no way to transform NaN to "".  Using `Controller` doesn't work well because the controlled component needs to update every keypress, and a string ending in a decimal separator isn't distinguished as a float from a string not ending in a decimal separator.

Will I work around this using a custom component and react state?   Probably.

But I don't see this as a particularly strange use case, and I think that the danger of bloating the API can be cut down by including flexible parameters, like `transform` and `parse` fields of `register`, which would then eliminate people asking for options on how to display NaN, etc.  Furthermore, it would add real functionality in how people can use uncontrolled components.

**Comment by bluebill1049** [comment]
Read the doc on setValueAs api

**Comment by david-morris** [comment]
Thanks, @bluebill1049 !  I don't know how many times I've read the options of `register` without noticing `setValueAs`.  

But that seems to only do parse, while the core of my problem is with the transform half, since my problem is with using react-hook-form as a single source of truth and wanting to display a value set as NaN as "".  

In my particular case I think I'll be able to use the `value` parameter to set "" as the displayed value when I start with NaN, but that wouldn't work if I could ever go from a number value to a NaN.  Is there something I'm missing about `setValueAs`, or possibly uncontrolled components and how they synchronize with react-hook-form values in general?

**Comment by david-morris** [comment]
I just want to update this thread with the results of my work.  What I was trying to do was to use Chakra NumberInput with react-hook-form uncontrolled component `register`.  I determined this wasn't possible, and instead wrote a controlled component directly wrapping Chakra Input.

On one hand, this indicates that transform and parse would be new functionality on uncontrolled inputs.  On the other hand, it also may suggest that fundamentally, what I was writing was a controlled component.  I don't know enough about JS to talk about the performance implications of this, but if you're trying to do something similar as a user, I suggest you skip straight to the `useController` API and writing your own custom controlled component.
