### ISSUE TITLE
Failed to minify the code from this file

### ISSUE THREAD

**Issue by pabloibanezcom** [bluebill1049/react-hook-form#66]
**Copy of issue #50** 

Hi,

Great work doing this, I've been using it for form building in my app. However I'm having one important issue when running npm run build (the app was created with create-react-app). The issue is:

Failed to minify the code from this file:

        ./node_modules/react-hook-form/dist/index.es.js:9:44
I've tried updating react-scripts to v.2.0.0 but the problem remains. Any idea how to solve this?

**Comment by pabloibanezcom** [comment]
@bluebill1049 You can find the package.json (and the entire repo) here https://github.com/pabloibanezcom/tube-map-history.web

Many thanks in advance

**Comment by bluebill1049** [comment]
I see the problem now, it's not create-react-app. it's your webpack config because you had ejected before
<img width="393" alt="Screen Shot 2019-06-09 at 9 33 41 am" src="https://user-images.githubusercontent.com/10513364/59153321-ae468f80-8a99-11e9-8aef-ff89222056f6.png">
.

you may want to look into the loader.

**Comment by pabloibanezcom** [comment]
This works to me now after migrating the app to the newest create-react-app boilerplate. This works even after doing eject.

Thanks for the support.

**Comment by bluebill1049** [comment]
No worries, If you find the package useful please star the repo to support and share around the community. many thanks 👍
